% mexComputeSTVKGradHess2D.cpp - computes negative area weighted STVK dpsidF and d2psidF2
%
% [ ii, jj, Cvals, dpsidF ] = mexNeoHookean2D( F, A, mu, lambda );
%
% Input:
%  F        4x#E deformation gradient of each element (or a vector of size 4x#E)
%  A        #E area of each element
%  mu       #E lamé parameter of each element
%  lambda   #E lamé parameter of each element
% 
% Output:
%  ii         16x#E by 1 row indices for each C block in a sparse matrix
%  jj         16x#E by 1 col indices for each C block in a sparse matrix
%  Cvals      16x#E by 1 energy Hessian wrt F for each eleemnt (scaled by negative area)
%  dpsidF     4x#E by 1 energy gradient (scaled by negative area)
%
% To compile type: mex -R2018a mexNeoHookean2D.cpp
%
% Notes:
%
% Code generated by scratch/mexNeoHookean2D.m
%