function [R] = RotationMatrixDegrees(degrees)
% RotationMatrixDegrees Computes a rotation matrix from Euler angles
%
%  [R] = RotationMatrixDegrees(degrees)
%
%       degrees   3 element vector containing X Y and Z rotation
%
%       R = Rx * Ry * Rz

    c = cosd( degrees(1) );
    s = sind( degrees(1) );
    Rx = [...
            1  0  0; ...
            0  c -s; ...
            0  s  c ...
            ];
    c = cosd( degrees(2) );
    s = sind( degrees(2) );
    Ry = [...
            c  0  s; ...
            0  1  0; ...
           -s  0  c ...
            ];
    c = cosd( degrees(3) );
    s = sind( degrees(3) );
    Rz = [...
            c -s  0; ...
            s  c  0; ...
            0  0  1 ...
            ];
    R = Rx * Ry * Rz;
end

